easy_admin:
    design:
        menu:
            - { label: menu.content }
            - { entity: 'Advert', icon: 'newspaper-o', label: entity.advert.list }
            - label: menu.lib
              icon: 'book'
              children:
                  - { entity: 'Article', icon: 'book', label: entity.article.list }
                  - { entity: 'Tag', icon: 'tag', label: entity.tag.list }
                  - { entity: 'ArticleCategory', icon: 'bookmark', label: entity.category.list }
            - label: menu.shop
              icon: 'shopping-basket'
              children:
                  - { entity: 'Product', icon: 'shopping-bag', label: entity.product.list }
            - { entity: 'Gallery', icon: 'instagram', label: entity.gallery.list }
            - { label: menu.settings }
            - { entity: 'Setting', icon: 'cog', label: entity.setting.list }
            - { entity: 'TemplateImage', icon: 'image', label: entity.templateImage.list }
            - { entity: 'Contact', icon: 'address-card', label: entity.contact.list }
            - { entity: 'SocialLink', icon: 'group', label: entity.socialLink.list }
            - { entity: 'PageMetaInfo', icon: 'info-circle', label: entity.pageMetaInfo.list }
            - { label: menu.clients }
            - { entity: 'Ticket', icon: 'sticky-note', label: entity.ticket.list, default: true }
            - { label: menu.statistics }
            - { label: link.GA, url: 'https://analytics.google.com/', icon: 'line-chart', target: '_blank' }