security:
    providers:
        jwt:
            id: App\Http\Security\JWTIdentityProvider
    encoders:
        App\Http\Security\JWTIdentity:
            id: Symfony\Component\Security\Core\Encoder\PasswordEncoderInterface
    firewalls:

        login:
            pattern:  ^/rest/login
            stateless: true
            anonymous: true
            json_login:
                check_path:      /rest/login
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        rest:
            pattern:   ^/rest
            stateless: true
            anonymous: ~
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
                provider: jwt
