language: php
php:
  - '7.2'
  - '7.3'

jobs:
  include:
    - stage: lint
      before-script: composer install -o
      script: php vendor/bin/ecs check src
    - stage: test
      before-script: composer install -o
      script: php bin/phpunit
