language: php
php:
  - '7.2'

jobs:
  include:
    - stage: lint
      install: composer install -o
      script: php vendor/bin/ecs check src
    - stage: test
      install: composer install -o
      script: php bin/phpunit
