language: php
php:
  - '7.2'

services:
  - mysql

before_install:
  - npm install -g yarn

jobs:
  include:
    - stage: lint back
      install: composer install -o
      script: php vendor/bin/ecs check {src,tests}
    - stage: test back
      before_install:
        - mysql -e 'CREATE DATABASE caracal_test;'
      install: composer install -o
      script: php bin/phpunit
    - stage: analysis back
      install: composer install -o
      script: php vendor/bin/psalm

    - stage: lint front
      install: yarn
      script: yarn lint
    - stage: check front size
      install: yarn
      script: yarn size
