easy_admin:
    entities:
        Ticket:
            class: AppBundle\Entity\Ticket
            label: entity.ticket.title
            list:
                title: entity.ticket.list
                sort: 'createdAt'
                fields:
                    - createdAt
                    - answered
                    - customerName
                    - customerEmail
                    - customerMessage
            form:
                title: entity.ticket.form
                fields:
                    - { type: 'group', css_class: 'col-sm-12 col-md-8', label: form.customer, icon: 'user' }
                    - customerName
                    - customerEmail
                    - customerMessage
                    - { type: 'group', css_class: 'col-sm-12 col-md-4', label: form.general, icon: 'info' }
                    - createdAt
                    - answered