easy_admin:
    site_name: 'Caracal CMS'
    design:
        form_theme:   'vertical'
        color_scheme: 'light'
        brand_color: '#9c27b0'
        assets:
            favicon: '/bundles/app/admin/favicon.png'