easy_admin:
    design:
        menu:
            - { label: menu.content }
            - { entity: 'Tag', icon: 'tag', label: entity.tag.list }
            - { entity: 'Article', icon: 'book', label: entity.article.list }
            - { label: 'Site settings' }
            - { label: 'Settings', entity: 'Setting', icon: 'cog', params: { sortField: 'type' } }
            - { label: 'Template images', entity: 'TemplateImage', icon: 'image', params: { sortField: 'type' } }
            - { label: 'Contacts', entity: 'Contact', icon: 'address-card', params: { sortField: 'type' } }
            - { label: 'Social Links', entity: 'SocialLink', icon: 'group', params: { sortField: 'title' } }
            - { label: menu.clients }
            - { entity: 'Ticket', icon: 'sticky-note', label: entity.ticket.list, default: true }
            - { label: menu.statistics }
            - { label: link.GA, url: 'https://analytics.google.com/', icon: 'line-chart', target: '_blank' }