easy_admin:
    design:
        menu:
            - { label: 'Site content' }
            - { entity: 'Tag', icon: 'tag', label: 'Tags', params: { sortField: 'title' } }
            - { entity: 'Article', icon: 'book', label: 'Articles', params: { sortField: 'createdAt' } }
            - { label: 'Site settings' }
            - { label: 'Settings', entity: 'Setting', icon: 'cog', params: { sortField: 'type' } }
            - { label: 'Template images', entity: 'TemplateImage', icon: 'image', params: { sortField: 'type' } }
            - { label: 'Contacts', entity: 'Contact', icon: 'address-card', params: { sortField: 'type' } }
            - { label: 'Social Links', entity: 'SocialLink', icon: 'group', params: { sortField: 'title' } }
            - { label: 'Clients' }
            - { label: 'Tickets', entity: 'Ticket', icon: 'sticky-note', params: { sortField: 'createdAt' }, default: true }
            - { label: 'Statistics' }
            - { label: 'Google Analytics', url: 'https://analytics.google.com/', icon: 'line-chart', target: '_blank' }