easy_admin:
    design:
        menu:
            - { label: 'Site content' }
            - label: 'Products'
              icon: 'shopping-basket'
              children:
                  - { entity: 'Product', icon: 'th-list', label: 'List', params: { sortField: 'createdAt' }, default: true }
                  - { entity: 'Product', icon: 'plus-circle', label: 'Add', params: { action: 'new' } }