easy_admin:
    entities:
        Setting:
            class: AppBundle\Entity\Setting
            label: entity.setting.title
            disabled_actions: ['delete', 'new']
            list:
                title: entity.setting.list
                sort: type
                fields:
                    - title
                    - body
            form:
                title: entity.setting.form
                fields:
                    - { property: 'title', css_class: 'large', type: text, type_options: { disabled: true } }
                    - body