imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: admin/ }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    app.path.product_images:  /uploads/images/products
    app.path.template_images: /uploads/images/template
    app.path.gallery_images:  /uploads/images/gallery
    app.path.advert_images:   /uploads/images/advert
    app.path.article_images:  /uploads/images/article

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%', 'en'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        product_image_path: '%app.path.product_images%'
        template_image_path: '%app.path.template_images%'
        gallery_image_path: '%app.path.gallery_images%'
    paths:
        "%kernel.root_dir%/Resources/views/%app.current_theme%": THEME

# Doctrine Configuration
doctrine:
    dbal:
        types:
            enumcontacttype:       AppBundle\DBAL\EnumContactType
            enumsettingtype:       AppBundle\DBAL\EnumSettingType
            enumtemplateimagetype: AppBundle\DBAL\EnumTemplateImageType
        mapping_types:
            enum: string
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        cssrewrite: ~

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AppBundle\Entity\User
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"

vich_uploader:
    db_driver: orm
    mappings:
        product_images:
            uri_prefix:         '%app.path.product_images%'
            upload_destination: '%kernel.root_dir%/../web/uploads/images/products'
        template_images:
            uri_prefix:         '%app.path.template_images%'
            upload_destination: '%kernel.root_dir%/../web/uploads/images/template'
        gallery_images:
            uri_prefix:         '%app.path.gallery_images%'
            upload_destination: '%kernel.root_dir%/../web/uploads/images/gallery'
        advert_images:
            uri_prefix:         '%app.path.advert_images%'
            upload_destination: '%kernel.root_dir%/../web/uploads/images/advert'
        article_images:
            uri_prefix:         '%app.path.article_images%'
            upload_destination: '%kernel.root_dir%/../web/uploads/images/article'
