easy_admin:
    entities:
        ArticleCategory:
            class: AppBundle\Entity\ArticleCategory
            label: 'Article Category'
            list:
                title: 'Article Category'
                fields:
                    - title
                    - articles
            show:
                fields:
                    - { property: 'title', css_class: 'large' }
            form:
                fields:
                    - { property: 'title', css_class: 'large' }