easy_admin:
    entities:
        Article:
            class: AppBundle\Entity\Article
            label: 'Article'
            list:
                title: 'Article'
                fields:
                    - title
                    - createdAt
                    - { property: 'enabled', label: 'Published' }
                    - category
                    - hero
            form:
                fields:
                    - { type: 'group', css_class: 'col-sm-12 col-md-6', label: 'General information', icon: 'info' }
                    - { property: 'title', css_class: 'large' }
                    - createdAt
                    - tags
                    - { type: 'group', css_class: 'col-sm-12 col-md-6', label: 'Additional information', icon: 'info' }
                    - hero
                    - { property: 'enabled', label: 'Published' }
                    - { property: 'imageFile', type: 'vich_image' }
                    - { type: 'group', css_class: 'col-sm-12', label: 'Content', icon: 'book' }
                    - description