easy_admin:
    entities:
        BottomLink:
            class: AppBundle\Entity\BottomLink
            label: 'BottomLink'
            list:
                title: 'Links'
                fields:
                    - priority
                    - title
                    - link
            show:
                fields:
                    - priority
                    - title
                    - link
            form:
                fields:
                    - { property: 'title', css_class: 'large' }
                    - link
                    - priority