easy_admin:
    entities:
        Contact:
            class: AppBundle\Entity\Contact
            label: 'Contacts'
            disabled_actions: ['delete', 'new']
            list:
                fields:
                    - title
                    - body
            show:
                fields:
                    - { property: 'type', css_class: 'large' }
                    - body
            form:
                fields:
                    - { property: 'title', css_class: 'large', type_options: { disabled: true } }
                    - body