easy_admin:
    entities:
        Product:
            class: AppBundle\Entity\Product
            label: 'Product'
            list:
                title: 'Products'
                fields:
                    - id
                    - enabled
                    - title
                    - price
                    - { property: 'image', type: 'image', base_path: '%app.path.product_images%' }
            show:
                fields:
                    - id
                    - { property: 'title', css_class: 'large' }
                    - { property: 'enabled', label: 'Published' }
                    - price
                    - description
                    - { property: 'image', type: 'image', base_path: '%app.path.product_images%' }
            form:
                fields:
                    - { property: 'title', css_class: 'large' }
                    - { property: 'enabled', label: 'Published' }
                    - price
                    - description
                    - { property: 'imageFile', type: 'vich_image', type_options: { required: true } }