easy_admin:
    entities:
        Product:
            class: AppBundle\Entity\Product
            label: 'Products'
            list:
                fields:
                    - id
                    - title
            show:
                fields:
                    - id
                    - { property: 'title', css_class: 'large' }
            form:
                fields:
                    - { type: 'group', css_class: 'col-sm-8', label: 'Basic information', icon: 'pencil' }
                    - { property: 'title', css_class: 'large' }