easy_admin:
    entities:
        Product:
            class: AppBundle\Entity\Product
            label: 'Product'
            list:
                title: 'Products'
                fields:
                    - id
                    - title
            show:
                fields:
                    - id
                    - { property: 'title', css_class: 'large' }
            form:
                fields:
                    - { property: 'title', css_class: 'large' }