easy_admin:
    entities:
        Setting:
            class: AppBundle\Entity\Setting
            label: 'Settings'
            disabled_actions: ['delete', 'new']
            list:
                fields:
                    - title
                    - body
            form:
                fields:
                    - { property: 'title', css_class: 'large', type: text, type_options: { disabled: true } }
                    - body