easy_admin:
    entities:
        Tag:
            class: AppBundle\Entity\Tag
            label: 'Tag'
            list:
                title: 'Tag'
                fields:
                    - title
            form:
                fields:
                    - { type: 'group', css_class: 'col-sm-12', label: 'General information', icon: 'info' }
                    - { property: 'title', css_class: 'large' }