easy_admin:
    entities:
        Tag:
            class: AppBundle\Entity\Tag
            label: 'Tag'
            list:
                title: 'Tag'
                fields:
                    - id
                    - title
            show:
                fields:
                    - id
                    - { property: 'title', css_class: 'large' }
            form:
                fields:
                    - { property: 'title', css_class: 'large' }