easy_admin:
    entities:
        Gallery:
            class: AppBundle\Entity\Gallery
            label: entity.gallery.title
            list:
                title: entity.gallery.list
                sort: year
                fields:
                    - year
                    - title
                    - general
                    - images
            form:
                title: entity.gallery.form
                fields:
                    - { type: 'group', css_class: 'col-sm-12 col-md-6', label: form.general, icon: 'info' }
                    - title
                    - year
                    - general
                    - description
                    - { type: 'group', css_class: 'col-sm-12 col-md-6', label: Images, icon: 'instagram' }
                    - { property: 'images', type: 'collection', type_options: { entry_type: 'AppBundle\Form\ImageType', by_reference: false }}