easy_admin:
    entities:
        Contact:
            class: AppBundle\Entity\Contact
            label: entity.contact.title
            disabled_actions: ['delete', 'new']
            list:
                title: entity.contact.list
                sort: type
                fields:
                    - title
                    - body
            form:
                title: entity.contact.form
                fields:
                    - { type: 'group', css_class: 'col-sm-12', label: form.general, icon: 'info' }
                    - { property: 'title', type: 'text', type_options: { disabled: true } }
                    - body