easy_admin:
    entities:
        PageMetaInfo:
            class: AppBundle\Entity\PageMetaInfo
            label: entity.pageMetaInfo.title
            list:
                title: entity.pageMetaInfo.list
                sort: path
                fields:
                    - path
                    - title
                    - keywords
                    - description
            form:
                title: entity.pageMetaInfo.form
                fields:
                    - { type: 'group', css_class: 'col-sm-12', label: form.general, icon: 'info' }
                    - path
                    - title
                    - keywords
                    - description