easy_admin:
    entities:
        SocialLink:
            class: AppBundle\Entity\SocialLink
            label: entity.socialLink.title
            list:
                title: entity.socialLink.list
                sort: title
                fields:
                    - title
                    - url
                    - faIcon
            form:
                title: entity.socialLink.form
                fields:
                    - { type: 'group', css_class: 'col-sm-12 col-md-6', label: form.general, icon: 'info' }
                    - title
                    - url
                    - { type: 'group', css_class: 'col-sm-12 col-md-6', label: form.additional, icon: 'info' }
                    - faIcon