easy_admin:
    design:
        menu:
            - { label: menu.content }
            - { entity: 'Tag', icon: 'tag', label: entity.tag.list }
            - { entity: 'Article', icon: 'book', label: entity.article.list }
            - { label: menu.settings }
            - { entity: 'Setting', icon: 'cog', label: entity.setting.list }
            - { entity: 'TemplateImage', icon: 'image', label: entity.templateImage.list }
            - { entity: 'Contact', icon: 'address-card', label: entity.contact.list }
            - { entity: 'SocialLink', icon: 'group', label: entity.socialLink.list }
            - { entity: 'PageMetaInfo', icon: 'info-circle', label: entity.pageMetaInfo.list }
            - { label: menu.clients }
            - { entity: 'Ticket', icon: 'sticky-note', label: entity.ticket.list, default: true }
            - { label: menu.statistics }
            - { label: link.GA, url: 'https://analytics.google.com/', icon: 'line-chart', target: '_blank' }