easy_admin:
    entities:
        Contact:
            class: AppBundle\Entity\Contact
            label: entity.contact.title
            disabled_actions: ['delete', 'new']
            list:
                title: entity.contact.list
                sort: type
                fields:
                    - title
                    - body
            form:
                title: entity.contact.form
                fields:
                    - { property: 'title', css_class: 'large', type_options: { disabled: true } }
                    - body