controllers:
    resource: '../src/Http/'
    type: annotation

rest_login_check:
    path: /api/login

admin_app:
  path: /{path}
  requirements:
    path: .*
  defaults: { _controller: App\Http\Controller\AdminController:index }
