parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/*'
        exclude: '../src/{Migrations,Util,Kernel.php}'

    App\Http\Controller\:
        resource: '../src/Http/Controller'
        tags: ['controller.service_arguments']

    App\Http\ResponseFormalizer\ResponseFormalizerSubscriber:
        arguments: [!tagged app.response_formalizer]

    _instanceof:
        Symfony\Component\HttpKernel\Controller\ArgumentValueResolverInterface:
            tags: ['controller.argument_value_resolver']
        App\Http\ResponseFormalizer\ResponseFormalizerInterface:
            tags: ['app.response_formalizer']