parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
           $projectDir: '%kernel.project_dir%'

    _instanceof:
      Symfony\Component\HttpKernel\Controller\ArgumentValueResolverInterface:
        tags: ['controller.argument_value_resolver']
      Kamyshev\ResponderBundle\Responder\ResponderInterface:
        tags: ['kamyshev.responder']
      Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository:
        tags: ['doctrine.repository_service']

    App\:
        resource: '../src/*'
        exclude: '../src/{Migrations,Util,Kernel.php}'

    App\Http\Controller\:
        resource: '../src/Http/Controller'
        tags: ['controller.service_arguments']

    # Serializer
    datetime_normalizer:
        class: Symfony\Component\Serializer\Normalizer\DateTimeNormalizer
        tags:
            - { name: 'serializer.normalizer', priority: 100 }
    App\Command\DataCommandDenormalizer:
        tags:
            - { name: 'serializer.normalizer', priority: 3 }
    App\Command\DeleteCommandDenormalizer:
        tags:
            - { name: 'serializer.normalizer', priority: 3 }
    property_normalizer:
        class: Symfony\Component\Serializer\Normalizer\PropertyNormalizer
        tags:
            - { name: 'serializer.normalizer', priority: 2 }
    object_normalizer:
        class: Symfony\Component\Serializer\Normalizer\ObjectNormalizer
        tags:
            - { name: 'serializer.normalizer', priority: 1 }

    # Http
    App\Http\FileUploader\RemoteFileUploader: ~
    App\Http\FileUploader\FileUploader: '@App\Http\FileUploader\RemoteFileUploader'

    # Common
    App\Service\IdGenerator\NanoIdGenerator: ~
    App\Service\IdGenerator\IdGenerator: '@App\Service\IdGenerator\NanoIdGenerator'

    App\Service\ObjectStorageClient\DigitalOceanSpacesClient:
        arguments: ['%env(DO_BUCKET)%', '%env(DO_REGION)%', '%env(DO_API_KEY)%', '%env(DO_SECRET_KEY)%']
    App\Service\ObjectStorageClient\ObjectStorageClient: '@App\Service\ObjectStorageClient\DigitalOceanSpacesClient'

    # Default password encoder
    Symfony\Component\Security\Core\Encoder\PasswordEncoderInterface:
        class: Symfony\Component\Security\Core\Encoder\BCryptPasswordEncoder
        arguments: [12]