parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/*'
        exclude: '../src/{Migrations,Util,Kernel.php}'

    App\Http\Controller\:
        resource: '../src/Http/Controller'
        tags: ['controller.service_arguments']

    _instanceof:
        Symfony\Component\HttpKernel\Controller\ArgumentValueResolverInterface:
            tags: ['controller.argument_value_resolver']
        Kamyshev\ResponderBundle\Responder\ResponderInterface:
            tags: ['kamyshev.responder']

    # Serializer

    datetime_normalizer:
        class: Symfony\Component\Serializer\Normalizer\DateTimeNormalizer
        tags:
            - { name: 'serializer.normalizer', priority: 100 }

    object_normalizer:
        class: Symfony\Component\Serializer\Normalizer\ObjectNormalizer
        tags: ['serializer.normalizer']
