easy_admin:
    entities:
        Article:
            class: AppBundle\Entity\Article
            label: entity.article.title
            list:
                title: entity.article.list
                sort: createdAt
                fields:
                    - title
                    - createdAt
                    - { property: 'enabled', label: 'Published' }
                    - tags
                    - hero
            form:
                title: entity.article.form
                fields:
                    - { type: 'group', css_class: 'col-sm-12 col-md-6', label: form.general, icon: 'info' }
                    - { property: 'title', css_class: 'large' }
                    - createdAt
                    - tags
                    - { type: 'group', css_class: 'col-sm-12 col-md-6', label: form.additional, icon: 'info' }
                    - hero
                    - { property: 'enabled', label: 'Published' }
                    - { property: 'imageFile', type: 'vich_image' }
                    - { type: 'group', css_class: 'col-sm-12', label: form.body, icon: 'book' }
                    - description